anykernel: Nexus -> Mimir (Best)
* Changed some props to ensure banner and kernel integration and initialization.

Change-Id: Id0b03b5b383c3536bae149167e9bfd6e85b6313f
Signed-off-by: Vhmit <viktor.9630@hotmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -23,44 +23,13 @@ ui_print() {
     shift;
   done;
 }
-
 ui_printfile() {
   while IFS='' read -r line || $BB [[ -n "$line" ]]; do
     ui_print "$line";
   done < $1;
 }
-
-# insert_line <file> <if search string> <before|after> <line match string> <inserted line>
-insert_line() {
-  local offset line;
-  if ! grep -q "$2" $1; then
-    case $3 in
-      before) offset=0;;
-      after) offset=1;;
-    esac;
-    line=$((`grep -n "$4" $1 | head -n1 | cut -d: -f1` + offset));
-    if [ -f $1 -a "$line" ] && [ "$(wc -l $1 | cut -d\  -f1)" -lt "$line" ]; then
-      echo "$5" >> $1;
-    else
-      sed -i "${line}s;^;${5}\n;" $1;
-    fi;
-  fi;
-}
-
-ui_print "××××××××××××××××××××××××××××××××××××××××××××××"
-ui_print "              _   __                                "
-ui_print "             / | / /__  _  ____  _______             "
-ui_print "            /  |/ / _ \| |/_/ / / / ___/              "
-ui_print "           / /|  /  __/>  </ /_/ (__  )              "
-ui_print "          /_/ |_/\___/_/|_|\__,_/____/                "
-ui_print "                                                    "
-ui_print "×××××××××××××××××××××××××××××××××××××××××××××××"
-ui_print "×              Nexus Kernel Lavender              ×"
-ui_print "×××××××××××××××××××××××××××××××××××××××××××××××"
-ui_print " "
-ui_print "× Initializing parameters and properties"
 show_progress() { echo "progress $1 $2" >> $OUTFD; }
-file_getprop() { $BB grep "^$2=" "$1" | $BB tail -n1 | $BB cut -d= -f2-; }
+file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
 find_slot() {
   local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
   [ "$slot" ] || slot=$($BB grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | $BB cut -d\  -f1 | $BB cut -d= -f2);
@@ -83,26 +52,25 @@ mount_apex() {
   [ -d /system_root/system/apex ] || return 1;
   local apex dest loop minorx num var;
   setup_mountpoint /apex;
-  $BB mount -t tmpfs tmpfs /apex -o mode=755 && $BB touch /apex/apextmp;
   minorx=1;
   [ -e /dev/block/loop1 ] && minorx=$($BB ls -l /dev/block/loop1 | $BB awk '{ print $6 }');
   num=0;
   for apex in /system_root/system/apex/*; do
-    dest=/apex/$($BB basename $apex | $BB sed -E -e 's;\.apex$|\.capex$;;' -e 's;\.current$|\.release$;;');
+    dest=/apex/$($BB basename $apex .apex);
+    case $dest in
+      *.current|*.release) dest=$(echo $dest | $BB rev | $BB cut -d. -f2- | $BB rev);;
+    esac;
     $BB mkdir -p $dest;
     case $apex in
-      *.apex|*.capex)
-        $BB unzip -qo $apex original_apex -d /apex;
-        [ -f /apex/original_apex ] && apex=/apex/original_apex;
+      *.apex)
         $BB unzip -qo $apex apex_payload.img -d /apex;
-        $BB mv -f /apex/original_apex $dest.apex 2>/dev/null;
         $BB mv -f /apex/apex_payload.img $dest.img;
         $BB mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
         if [ $? != 0 ]; then
           while [ $num -lt 64 ]; do
             loop=/dev/block/loop$num;
-            [ -e $loop ] || $BB mknod $loop b 7 $((num * minorx));
-            $BB losetup $loop $dest.img 2>/dev/null;
+            ($BB mknod $loop b 7 $((num * minorx));
+            $BB losetup $loop $dest.img) 2>/dev/null;
             num=$((num + 1));
             $BB losetup $loop | $BB grep -q $dest.img && break;
           done;
@@ -121,9 +89,9 @@ mount_apex() {
   $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB sed 's; /;=/;'); unset export;
 }
 umount_apex() {
-  [ -d /apex ] || return 1;
+  [ -d /apex/com.android.runtime ] || return 1;
   local dest loop var;
-  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc 2>/dev/null | $BB awk '{ print $2 }'); do
+  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB awk '{ print $2 }'); do
     if [ "$(eval echo \$OLD_$var)" ]; then
       eval $var=\$OLD_${var};
     else
@@ -132,32 +100,28 @@ umount_apex() {
     unset OLD_${var};
   done;
   for dest in $($BB find /apex -type d -mindepth 1 -maxdepth 1); do
-    loop=$($BB mount | $BB grep $dest | $BB grep loop | $BB cut -d\  -f1);
-    $BB umount -l $dest;
-    [ "$loop" ] && $BB losetup -d $loop;
+    if [ -f $dest.img ]; then
+      loop=$($BB mount | $BB grep $dest | $BB cut -d\  -f1);
+    fi;
+    ($BB umount -l $dest;
+    $BB losetup -d $loop) 2>/dev/null;
   done;
-  [ -f /apex/apextmp ] && $BB umount /apex;
   $BB rm -rf /apex 2>/dev/null;
 }
 mount_all() {
-  local byname mount slot system;
   if ! is_mounted /cache; then
     $BB mount /cache 2>/dev/null && UMOUNT_CACHE=1;
   fi;
   if ! is_mounted /data; then
     $BB mount /data && UMOUNT_DATA=1;
   fi;
-  (for mount in /vendor /product /system_ext /persist; do
-    $BB mount -o ro -t auto $mount;
-  done) 2>/dev/null;
+  ($BB mount -o ro -t auto /vendor;
+  $BB mount -o ro -t auto /product;
+  $BB mount -o ro -t auto /persist) 2>/dev/null;
   setup_mountpoint $ANDROID_ROOT;
   if ! is_mounted $ANDROID_ROOT; then
     $BB mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
   fi;
-  byname=bootdevice/by-name;
-  [ -d /dev/block/$byname ] || byname=$($BB find /dev/block/platform -type d -name by-name 2>/dev/null | $BB head -n1 | $BB cut -d/ -f4-);
-  [ -d /dev/block/mapper ] && byname=mapper;
-  [ -e /dev/block/$byname/system ] || slot=$(find_slot);
   case $ANDROID_ROOT in
     /system_root) setup_mountpoint /system;;
     /system)
@@ -171,24 +135,28 @@ mount_all() {
       if [ $? != 0 ]; then
         ($BB umount /system;
         $BB umount -l /system) 2>/dev/null;
-        $BB mount -o ro -t auto /dev/block/$byname/system$slot /system_root;
+        if [ -d /dev/block/mapper ]; then
+          [ -e /dev/block/mapper/system ] || local slot=$(find_slot);
+          $BB mount -o ro -t auto /dev/block/mapper/vendor$slot /vendor;
+          $BB mount -o ro -t auto /dev/block/mapper/product$slot /product 2>/dev/null;
+          $BB mount -o ro -t auto /dev/block/mapper/system$slot /system_root;
+        else
+          [ -e /dev/block/bootdevice/by-name/system ] || local slot=$(find_slot);
+          ($BB mount -o ro -t auto /dev/block/bootdevice/by-name/vendor$slot /vendor;
+          $BB mount -o ro -t auto /dev/block/bootdevice/by-name/product$slot /product;
+          $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist$slot /persist) 2>/dev/null;
+          $BB mount -o ro -t auto /dev/block/bootdevice/by-name/system$slot /system_root;
+        fi;
       fi;
     ;;
   esac;
-  [ -f /system_root/system/build.prop ] && system=/system;
-  for mount in /vendor /product /system_ext; do
-    if ! is_mounted $mount && [ -L /system$mount -o -L /system_root$system$mount ]; then
-      setup_mountpoint $mount;
-      $BB mount -o ro -t auto /dev/block/$byname$mount$slot $mount;
-    fi;
-  done;
   if is_mounted /system_root; then
     mount_apex;
-    $BB mount -o bind /system_root$system /system;
-  fi;
-  if ! is_mounted /persist && [ -e /dev/block/bootdevice/by-name/persist ]; then
-    setup_mountpoint /persist;
-    $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist /persist;
+    if [ -f /system_root/build.prop ]; then
+      $BB mount -o bind /system_root /system;
+    else
+      $BB mount -o bind /system_root/system /system;
+    fi;
   fi;
 }
 umount_all() {
@@ -204,7 +172,7 @@ umount_all() {
   fi;
   umount /vendor; # busybox umount /vendor breaks recovery on some hacky devices
   umount -l /vendor;
-  for mount in /mnt/system /mnt/vendor /product /mnt/product /system_ext /mnt/system_ext /persist; do
+  for mount in /mnt/system /mnt/vendor /product /mnt/product /persist; do
     $BB umount $mount;
     $BB umount -l $mount;
   done;
@@ -234,7 +202,7 @@ setup_env() {
   if [ ! "$(getprop 2>/dev/null)" ]; then
     getprop() {
       local propdir propfile propval;
-      for propdir in / /system_root /system /vendor /product /system_ext /odm; do
+      for propdir in / /system_root /system /vendor /odm /product; do
         for propfile in default.prop build.prop; do
           if [ "$propval" ]; then
             break 2;
@@ -265,7 +233,7 @@ restore_env() {
   unset OLD_LD_PATH OLD_LD_PRE OLD_LD_CFG;
   umount_all;
   [ -L /etc_link ] && $BB rm -rf /etc/*;
-  (for dir in /etc /apex /system_root /system /vendor /product /system_ext /persist; do
+  (for dir in /apex /system /system_root /etc; do
     if [ -L "${dir}_link" ]; then
       rmdir $dir;
       $BB mv -f ${dir}_link $dir;
@@ -274,9 +242,9 @@ restore_env() {
   $BB umount -l /dev/random) 2>/dev/null;
 }
 debugging() {
-  case $($BB basename "$ZIPFILE" .zip) in
+  case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print "× Creating debugging archive in $DIR!";
+      ui_print " " "Creating debugging archive in $DIR...";
       [ -f /tmp/recovery.log ] && local log=/tmp/recovery.log;
       $BB tar -czf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $AKHOME $log;
     ;;
@@ -298,21 +266,22 @@ abort() {
 do_devicecheck() {
   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
   local device devicename match product testname vendordevice vendorproduct;
+  ui_print " - Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
   vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
-  for testname in $($BB grep '^device.name.*=' anykernel.sh | $BB cut -d= -f2-); do
+  for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "× Device recognised as $testname";
+        ui_print " - Device is $testname" " ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort "× Unsupported device. Aborting!";
+    abort " - Unsupported device. Aborting...";
   fi;
 }
 int2ver() {
@@ -327,7 +296,7 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "× Checking Android version";
+  ui_print "Checking Android version...";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -346,15 +315,15 @@ do_versioncheck() {
     done;
   fi;
   if [ "$supported" ]; then
-     ui_print "× Detected android version: $android_ver";
+    ui_print "$android_ver" " ";
   else
-    abort "× Unsupported Android version. Aborting!";
+    abort " - Unsupported Android version. Aborting...";
   fi;
 }
 do_levelcheck() {
   [ "$(file_getprop anykernel.sh supported.patchlevels)" ] || return 1;
   local android_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
-  ui_print "× Checking Android security patch level";
+  ui_print "Checking Android security patch level...";
   supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $BB grep -oE '[0-9]{4}-[0-9]{2}|-');
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | $BB grep -oE '[0-9]{4}-[0-9]{2}');
@@ -369,14 +338,13 @@ do_levelcheck() {
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
-    ui_print "× Detected android patch level: $android_lvl";
+    ui_print "$android_lvl" " ";
   else
-    abort "× Unsupported Android security patch level. Aborting!";
+    abort " - Unsupported Android security patch level. Aborting...";
   fi;
 }
 dump_moduleinfo() {
-$BB cat <<EOF > $1;
-id=ak3-helper
+cat <<EOF > $1;
 name=AK3 Helper Module
 version=$($BB awk '{ print $3 }' $AKHOME/vertmp) $($BB grep -oE '#.[0-9]' $AKHOME/vertmp)
 versionCode=1
@@ -385,7 +353,7 @@ description=$KERNEL_STRING
 EOF
 }
 dump_moduleremover() {
-$BB cat <<'EOF' > $1;
+cat <<'EOF' > $1;
 #!/system/bin/sh
 MODDIR=${0%/*};
 if [ "$(cat /proc/version)" != "$(cat $MODDIR/version)" ]; then
@@ -398,26 +366,26 @@ do_modules() {
   local block modcon moddir modtarget module slot umask;
   if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
     cd $AKHOME/modules;
-    ui_print "× Creating kernel helper Magisk module";
+    ui_print " - Creating kernel helper Magisk module...";
     if [ -d /data/adb/magisk -a -f $AKHOME/split_img/.magisk ]; then
       umask=$(umask);
       umask 022;
       moddir=/data/adb/modules/ak3-helper;
       $BB rm -rf $moddir;
-      $BB mkdir -p system $moddir;
+      mkdir -p system $moddir;
       ($BB mv -f product system;
       $BB mv -f vendor system) 2>/dev/null;
       $BB cp -rLf * $moddir;
       dump_moduleinfo $moddir/module.prop;
       dump_moduleremover $moddir/post-fs-data.sh;
-      $BB cp -f $AKHOME/vertmp $moddir/version;
+      cp -f $AKHOME/vertmp $moddir/version;
       umask $umask;
     else
-      ui_print "× Magisk installation not found. Skipped!";
+      ui_print " - Magisk installation not found. Skipped!";
     fi;
   else
     cd $AKHOME/modules;
-    ui_print "Pushing modules...";
+    ui_print " " "Pushing modules...";
     if [ -d /dev/block/mapper ]; then
       for block in system vendor product; do
         for slot in "" _a _b; do
@@ -430,7 +398,7 @@ do_modules() {
       ($BB mount -o rw,remount -t auto /vendor;
       $BB mount -o rw,remount -t auto /product) 2>/dev/null;
     fi;
-    for module in $($BB find . -name '*.ko'); do
+    for module in $(find . -name '*.ko'); do
       modtarget=$POSTINSTALL$(echo $module | $BB cut -c2-);
       if [ ! -e $modtarget ]; then
         case $module in
@@ -442,7 +410,7 @@ do_modules() {
       if is_mounted $modtarget; then
         $BB mount -o rw,remount -t auto $modtarget;
       fi;
-      $BB mkdir -p $($BB dirname $modtarget);
+      mkdir -p $(dirname $modtarget);
       $BB cp -rLf $module $modtarget;
       $BB chown 0:0 $modtarget;
       $BB chmod 644 $modtarget;
@@ -462,23 +430,14 @@ do_modules() {
   cd $AKHOME;
 }
 
-print_extras()
-{
-  android_ver=$(file_getprop /system/build.prop ro.build.version.release);
-  android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
-
-  ui_print "× Detected android version: $android_ver";
-  ui_print "× Detected android patch level: $android_lvl";
-}
-
-show_progress 1.34 5;
-ui_print "";
+show_progress 1.34 4;
+ui_print " ";
 cleanup;
 mkdir -p $AKHOME/bin;
 cd $AKHOME;
 unzip -o "$ZIPFILE";
 if [ $? != 0 -o ! "$(ls tools)" ]; then
-  abort "× Unzip failed. Aborting!";
+  abort "Unzip failed. Aborting...";
 fi;
 for ARCH32 in x86 arm; do
   if [ -d $AKHOME/tools/$ARCH32 ]; then
@@ -496,17 +455,42 @@ chmod 755 $BB;
 $BB chmod -R 755 tools bin;
 $BB --install -s bin;
 if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "× Busybox setup failed. Aborting!";
+  abort "Busybox setup failed. Aborting...";
 fi;
+
+if [ -f banner ]; then
+  ui_printfile banner;
+  ui_print " " " ";
+fi;
+
+if [ -f version ]; then
+  ui_print " ";
+  ui_printfile version;
+  ui_print " ";
+fi;
+
+KERNEL_FOR="$(file_getprop anykernel.sh kernel.for)";
+KERNEL_COMPILER="$(file_getprop anykernel.sh kernel.compiler)";
+KERNEL_MADE="$(file_getprop anykernel.sh kernel.made)";
+KERNEL_VERSION="$(file_getprop anykernel.sh kernel.version)";
+DEVICE_NAME="$(file_getprop anykernel.sh device.name1)";
+ui_print "- Introducing $(file_getprop anykernel.sh kernel.string)";
+ui_print " ";
+ui_print "=======================================";
+ui_print "-- Kernel Version : $KERNEL_VERSION";
+ui_print "-- Variant        : $KERNEL_FOR";
+ui_print "-- Compiler       : $KERNEL_COMPILER";
+ui_print "-- Device         : $DEVICE_NAME";
+ui_print "-- Maintainer     : $KERNEL_MADE";
+ui_print "=======================================";
 
 setup_env;
 
 do_devicecheck;
 do_versioncheck;
 do_levelcheck;
-print_extras;
 
-ui_print "× Installing Linux kernel";
+ui_print " - Installing...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
@@ -523,9 +507,5 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print "× Successfully flashed kernel!";
-ui_print "× Thank you for using Nexus Kernel!";
-ui_print "× Powered by AnyKernel3 by osm0sis @ xda-developers";
-$BB grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
-ui_print " "
-ui_print "×××××××××××××××××××××××××××××××××××××××××××××××"
+ui_print " " " " "Done!";
+ui_print " " " " "Mimir Kernel was succesfully installed";
